### ISSUE TITLE
[PF Rennes] Pb envoi mail gestion des comptes LDAP

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/cadastrapp#109]
@pierrejego 

Pour la suite de mes tests j'ai besoin de créer un ou deux comptes.
Je les crée depuis LDAPadmin puis je fais un reset passwd pour obtenir un mdp.

Pb : le mail ne part pas :

```
java.io.IOException: org.georchestra.ldapadmin.ds.DataServiceException: org.georchestra.ogcservstatistics.dataservices.DataCommandException: ERREUR: la relation « ldapadmin.user_token » n'existe pas
  Position : 37
    at org.georchestra.ldapadmin.ws.passwordrecovery.PasswordRecoveryFormController.generateToken(PasswordRecoveryFormController.java:154)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:679)
Caused by: org.georchestra.ldapadmin.ds.DataServiceException: org.georchestra.ogcservstatistics.dataservices.DataCommandException: ERREUR: la relation « ldapadmin.user_token » n'existe pas
  Position : 37
    at org.georchestra.ldapadmin.ds.UserTokenDao.exist(UserTokenDao.java:161)
    at org.georchestra.ldapadmin.ws.passwordrecovery.PasswordRecoveryFormController.generateToken(PasswordRecoveryFormController.java:136)
    ... 33 more
Caused by: org.georchestra.ogcservstatistics.dataservices.DataCommandException: ERREUR: la relation « ldapadmin.user_token » n'existe pas
  Position : 37
    at org.georchestra.lib.sqlcommand.AbstractQueryCommand.execute(AbstractQueryCommand.java:54)
    at org.georchestra.ldapadmin.ds.UserTokenDao.exist(UserTokenDao.java:154)
    ... 34 more

Cookies:

JSESSIONID=[06334498B2511E8D552ABB06B7693988]
```

**Comment by pierrejego** [comment]
Il faut créer depuis la page du CAS, puis aller dans ldapadmin avec le compte admin pour les changer de groupes

Il n'y a pas de serveur de mail sur ce serveur de qualification

**Comment by landryb** [comment]
Pas un pbm de cadastrapp

**Comment by MaelREBOUX** [comment]
c'est bon : j'ai mon compte de test
