### ISSUE TITLE
[qgis]relevé propriété cassé sur certaines parcelles

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#115]
```
2015-12-02 09:21:24,024 [http-nio-8380-exec-19] DEBUG /createRelevePropriete - testadmin - ROLE_MOD_LDAPADMIN,ROLE_SV_ADMIN,ROLE_ADMINISTRA
TOR,ROLE_MOD_ANALYTICS,ROLE_EL_CAD_CNIL1,ROLE_EL_DEP_43,ROLE_EL_CAD_CNIL2,ROLE_MOD_EXTRACTORAPP -o.s.jdbc.core.JdbcTemplate - Executing pre
pared SQL statement [select distinct pnb.id_local, pnb.jdatat, pnb.ccopre, pnb.ccosec, pnb.dnupla, pnb.dnvoiri, pnb.dindic, pnb.natvoi||' '||pnb.dvoilib as voie, pnb.ccoriv, pnb.dparpi, pnb.gpafpd, pnb.ccostn, pnb.ccosub, pnb.cgrnum, pnb.dclssf, pnb.cnatsp, pnb.dcntsf, pnb.drcsuba, pnb.pdl, pnb.dnulot, pnbsufexo.ccolloc, pnbsufexo.jandeb, pnbsufexo.jfinex, pnbsufexo.fcexb, pnbsufexo.gnexts, pnb.dreflf, pnb.majposa, pnb.bisufad, pnb.bisufad_dep, pnb.bisufad_reg from cadastrapp_qgis.proprietenonbatie pnb, cadastrapp_qgis.proprietenonbatiesufexo pnbsufexo  where pnb.cgocommune = pnbsufexo.cgocommune and pnb.id_local=pnbsufexo.id_local and pnb.comptecommunal = ? ORDER BY ccosec, dnupla]   
2015-12-02 09:21:24,823 [http-nio-8380-exec-19] DEBUG /createRelevePropriete - testadmin - ROLE_MOD_LDAPADMIN,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR,ROLE_MOD_ANALYTICS,ROLE_EL_CAD_CNIL1,ROLE_EL_DEP_43,ROLE_EL_CAD_CNIL2,ROLE_MOD_EXTRACTORAPP -o.g.c.s.p.ReleveProprieteController - Get undeveloped property id : 2014430089000AB0013
2015-12-02 09:21:24,826 [http-nio-8380-exec-19] WARN  /createRelevePropriete - testadmin - ROLE_MOD_LDAPADMIN,ROLE_SV_ADMIN,ROLE_ADMINISTRATOR,ROLE_MOD_ANALYTICS,ROLE_EL_CAD_CNIL1,ROLE_EL_DEP_43,ROLE_EL_CAD_CNIL2,ROLE_MOD_EXTRACTORAPP -o.a.cxf.phase.PhaseInterceptorChain - Application {http://service.cadastrapp.georchestra.org/}BatimentController has thrown exception, unwinding now

.....
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at org.georchestra.cadastrapp.service.pdf.ReleveProprieteController.getReleveProprieteInformation(ReleveProprieteController.java:421) ~[ReleveProprieteController.class:na]
        at org.georchestra.cadastrapp.service.pdf.ReleveProprieteController.createRelevePDFPropriete(ReleveProprieteController.java:111) ~[ReleveProprieteController.class:na]

```

probleme de schéma de BDD ? Cast moche ? Uniquement dans un cerain cas d'exonération ? Sur certaines parcelles ca passe bien.

Je reproduis le pbm sur notre pf de test (cf l'id de compte communal au dessus) et celle de préprod avec toute l'auvergne. Evidemment, je peux faire des requetes dans la BDD pour voir quelle donnée pose pbm.. mais je pense que c'est une desynchro entre les 2 modeles:

```
script/arcopole/views/arcopoleProprieteNonBatieSufExo.sql:                      CAST (exosuf.rcexnba AS INTEGER) as fcexb,
script/qgis/views/qgisProprieteNonBatieSufExo.sql:                      sufex.fcexn as fcexb,
```

Dans le modele qgis, fcexn est un varchar(10).

**Comment by pierrejego** [comment]
Effectivement, il y a un soucis sur le type.
Je change ça.

**Comment by landryb** [comment]
Ok, après application du fix sur la préprod, ca a l'air corrigé !

**Comment by pierrejego** [comment]
:) plus rapide que moi j'ai pas encore déployé sur les qualifs pour tester en intégration, j'ai juste testé en local...

**Comment by landryb** [comment]
Du coup y'a une nouvelle exception, qui demande un autre fix dans le code java ?

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at org.georchestra.cadastrapp.service.pdf.ReleveProprieteController.getReleveProprieteInformation(ReleveProprieteController.java:454)
```

**Comment by pierrejego** [comment]
Bonjour,
pour moi cette anomalie est corrigé, il me semblait qu'on avait testé jeudi.
@landryb tu peux confirmer ?

**Comment by landryb** [comment]
A priori oui celle-ci c'était ok.
