### ISSUE TITLE
nombreux batiments dans un cimetière

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#137]
En mode connecté, je consulte les infos parcellaire sur le cimetière (AH n°2) du Puy en Velay (430157) :
- sur l'onglet parcelle je veux afficher le bordereau parcellaire, la fenêtre avec le choix "sans/avec données nominatives" s'ouvre , quelque soit mon choix, le pdf ne se génère pas !
- lorsque je bascule sur l'onglet Bâtiments, j'ai plus de 200 bâtiments listés (habitation, commerce, professionnels, etc...) !

**Comment by pierrejego** [comment]
Je fais faire le test sur ta plateforme, voir si j'ai un message d'erreur pour le PDF, et surtout comprendre comment il peut y a voir des batiments sur le cimitère...

**Comment by stous** [comment]
Je complète, sur la même parcelle (430157 AH 2) :
- onglet Bâtiment :relevé de propriété,  le pdf ne se génère pas
  onglet Bâtiment : le bouton Descriptif: affiche une fenêtre vide avec un entête 'batiment A- niveau 00 - porte 01001' quelques soit le bâtiment sélectionnée (sur une autre parcelle 430002 AC 242, en cliquant sur descriptif  j'ai une fenêtre vide avec la même entête 'batiment A- niveau 00 - porte 01001' )

**Comment by landryb** [comment]
> quelque soit mon choix, le pdf ne se génère pas !

Quand on a fait le test, il n'y avait ni erreur dans la console, ni requete réseau qui sortait - peut-etre un pbm de logique dans le callback de sortie de la fenetre ?

**Comment by pierrejego** [comment]
Erreur de commentaire, lié à la #138, ne pas en tenir compte

En faisant le test sur la plateforme, je peux voir une erreur avec un NoCalssDefFound

</pre><p><b>cause mère</b></p><pre>java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO

Est-ce que tu pourrais m'envoyer le fichier de log cadastrapp.log de la plateforme ?

Merci

**Comment by jusabatier** [comment]
Même problème constaté lors de l'impression de n'importe quel document en PDF.

Voici le log :

2016-02-22 12:37:15,749 [http-nio-8181-exec-10] ERROR /createBordereauParcellaire - julien.sabatier - ROLE_MOD_LDAPADMIN;ROLE_SV_ADMIN;ROLE_SV_USER;ROLE_EL_AGGLO_EDITOR;ROLE_EL_AGGLO_LE_PUY;ROLE_SOAP_OPENADS;ROLE_MOD_OPENADS;ROLE_TOOL_SHAPES;ROLE_MOD_EXTRACTORAPP;ROLE_SER_INFORMATIQUE;ROLE_WFS_WRITE;ROLE_TOOL_RIL;ROLE_MOD_TOOLBOX;ROLE_SER_URBANISME;ROLE_ADMINISTRATOR;ROLE_MOD_ANALYTICS -o.a.c.i.AbstractFaultChainInitiatorObserver - Error occurred during error handling, give up!
org.apache.cxf.interceptor.Fault: Could not initialize class javax.imageio.ImageIO
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163) ~[AbstractInvoker.class:3.0.4]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:129) ~[AbstractInvoker.class:3.0.4]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200) ~[JAXRSInvoker.class:3.0.4]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99) ~[JAXRSInvoker.class:3.0.4]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[ServiceInvokerInterceptor$1.class:3.0.4]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[ServiceInvokerInterceptor.class:3.0.4]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[PhaseInterceptorChain.class:3.0.4]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [ChainInitiationObserver.class:3.0.4]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251) [AbstractHTTPDestination.class:3.0.4]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [ServletController.class:3.0.4]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [ServletController.class:3.0.4]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [ServletController.class:3.0.4]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171) [CXFNonSpringServlet.class:3.0.4]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293) [AbstractHTTPServlet.class:3.0.4]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217) [AbstractHTTPServlet.class:3.0.4]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) [tomcat8-servlet-api-8.0.14.jar:na]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268) [AbstractHTTPServlet.class:3.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat8-websocket-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [tomcat8-catalina-8.0.14.jar:8.0.14]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081) [tomcat8-coyote-8.0.14.jar:8.0.14]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat8-coyote-8.0.14.jar:8.0.14]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat8-coyote-8.0.14.jar:8.0.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat8-coyote-8.0.14.jar:8.0.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat8-coyote-8.0.14.jar:8.0.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.0.14.jar:8.0.14]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at org.apache.xmlgraphics.image.loader.impl.imageio.ImageLoaderFactoryImageIO.getSupportedMIMETypes(ImageLoaderFactoryImageIO.java:39) ~[ImageLoaderFactoryImageIO.class:1.5]
	at org.apache.xmlgraphics.image.loader.impl.imageio.ImageLoaderFactoryImageIO.isAvailable(ImageLoaderFactoryImageIO.java:54) ~[ImageLoaderFactoryImageIO.class:1.5]
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.registerLoaderFactory(ImageImplRegistry.java:186) ~[ImageImplRegistry.class:1.5]
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.discoverClasspathImplementations(ImageImplRegistry.java:115) ~[ImageImplRegistry.class:1.5]
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<init>(ImageImplRegistry.java:79) ~[ImageImplRegistry.class:1.5]
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.<init>(ImageImplRegistry.java:88) ~[ImageImplRegistry.class:1.5]
	at org.apache.xmlgraphics.image.loader.spi.ImageImplRegistry.getDefaultInstance(ImageImplRegistry.java:97) ~[ImageImplRegistry.class:1.5]
	at org.apache.xmlgraphics.image.loader.ImageManager.<init>(ImageManager.java:63) ~[ImageManager.class:1.5]
	at org.apache.fop.apps.FopFactory.<init>(FopFactory.java:178) ~[FopFactory.class:na]
	at org.apache.fop.apps.FopFactory.newInstance(FopFactory.java:190) ~[FopFactory.class:na]
	at org.georchestra.cadastrapp.service.pdf.BordereauParcellaireController.createBordereauParcellaire(BordereauParcellaireController.java:92) ~[BordereauParcellaireController.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181) ~[AbstractInvoker.class:3.0.4]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97) ~[AbstractInvoker.class:3.0.4]
	... 37 common frames omitted

**Comment by jusabatier** [comment]
L'erreur avec le NoClassDefFound est due au problème de cette issue qui bloque toutes les impressions PDF : https://github.com/GFI-Informatique/cadastrapp/issues/138 

Pour ce qui est des nombreux batiments remontés sur la parcelle du cimetière, on a les mêmes qui remontent au niveau de celle de la mairie, et plus généralement pour toutes les parcelles appartenant à la commune. Je pense que les bâtiments affichés dans l'onglets Bâtiment représentent l'ensemble des possédés par le propriétaire de la parcelle et non uniquement ceux de la parcelle.

Je ne sais pas si ce comportement est logique pour l'utilisation métier, pour ma part, je m'attendais plus à voir seulement ceux qui sont sur la parcelle dans cet onglet.

**Comment by pierrejego** [comment]
Il y a une problème sur la jointure faite dans la méthode infoOngleBatimentList.
Elle ramène l'ensemble des propriétés baties des comptes communaux correspondant à la parcelle, et non uniquement la parcelle.
Correction en cours de test.

**Comment by pierrejego** [comment]
Reste à comprendre pourquoi la génération ne fonctionne pas.

**Comment by pierrejego** [comment]
Je viens de faire le test sur la plateforme http://georchestra.demo.craig.fr/mapfishapp/
J'ai une erreur 403, sur le fond de plan, mais autrement le PDF se génère bien.

**Comment by pierrejego** [comment]
@landryb on s'appelle Lundi matin ? pour voir si c'est toujours d'actualité sur ton serveur. Ce qui m'étonne c'est l'absence de trace et de requête.
C'est dans quel version de navigateur ? Je viens d'essayer IE 11, Firefox 41 et Chrome 49 mais je ne reproduis pas. Il me semble que j'avais reproduit la dernière fois

**Comment by jusabatier** [comment]
Avec https://github.com/GFI-Informatique/cadastrapp/pull/169 le cimetière du Puy ne remonte plus qu'un batiment, donc déjà ce problème semble réglé.

L'autre problème étant lié à https://github.com/GFI-Informatique/cadastrapp/issues/138, je pense que cette issue peut être fermée.

**Comment by MaelREBOUX** [comment]
@jusabatier @stous  peut-on fermer ce ticket ?

**Comment by jusabatier** [comment]
Oui, je pense que ce ticket peut être fermé

**Comment by landryb** [comment]
Je viens de refaire le test, c'est ok ici.
