### ISSUE TITLE
Export PDF BP ne fonctionne pas avec notre fond de plan

### ISSUE THREAD

**Issue by catmorales** [georchestra/cadastrapp#199]
```
2016-06-08 11:59:15,546 [http-8480-6] ERROR /getImageBordereau - nouser - norole -o.g.c.s.ImageParcelleController - Error while getting basemap image, no basemap will be displayed on image
org.geotools.ows.ServiceException: Error while parsing XML.
        at org.geotools.data.wms.response.WMSGetCapabilitiesResponse.<init>(WMSGetCapabilitiesResponse.java:58) ~[gt-wms-9.2.jar:na]
        at org.geotools.data.wms.WMS1_0_0$GetCapsRequest.createResponse(WMS1_0_0.java:234) ~[gt-wms-9.2.jar:na]
        at org.geotools.data.ows.AbstractOpenWebService.internalIssueRequest(AbstractOpenWebService.java:427) ~[gt-main-9.2.jar:na]
        at org.geotools.data.wms.WebMapServer.issueRequest(WebMapServer.java:419) ~[gt-wms-9.2.jar:na]
        at org.geotools.data.ows.AbstractOpenWebService.negotiateVersion(AbstractOpenWebService.java:260) ~[gt-main-9.2.jar:na]
        at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:110) ~[gt-main-9.2.jar:na]
        at org.geotools.data.ows.AbstractOpenWebService.<init>(AbstractOpenWebService.java:75) ~[gt-main-9.2.jar:na]
        at org.geotools.data.wms.WebMapServer.<init>(WebMapServer.java:370) ~[gt-wms-9.2.jar:na]
```

**Comment by catmorales** [comment]
fichier de conf qui pointe vers un aggrégat geoserver

```
## Use to create image for pdf on server side (could be use for client configuration as well)
## if baseMap URL is empty no image will be added in pdf
baseMap.WMS.url=https://portail-test.sig.rennesmetropole.fr/geoserver/wms?SERVICE=WMS&Request=GetCapabilities
baseMap.layer.name=ref_cad:Cadastre
baseMap.format=image/png
baseMap.SRS=EPSG:3857
```

**Comment by catmorales** [comment]
@pierrejego Serait ce lié au même problème d'authentification que  tu as réglé ici pour l'accès au service fonctionnel ?

```
## information about WMS and WFS service
# Here you can configure the layer name and with field contains the parcelle Id depending if you are on Qgis or Arcopole model
cadastre.wms.url=https://portail-test.sig.rennesmetropole.fr/geoserver/wms
cadastre.wms.layer.name=ref_cad:app_cadastrapp_parcelle
# only used when wms service need authentification
# if empty no authentification is used
cadastre.wms.username=xxxx
cadastre.wms.password=xxxx
```

**Comment by catmorales** [comment]
Après différents test , seul le fond de plan OSM fonctionne.
A noter: tous nos autres fonds de plans sont en https.

**Comment by pierrejego** [comment]
Effectivement , je n'ai pas rajouté l'authentification pour le fond de plan.

**Comment by pierrejego** [comment]
Je viens de faire les modifications nécessaire, par contre je n'ai pas de plateforme pour faire le test en https. Je vous laisser clore l'anomalie si c'est résolu.

**Comment by pierrejego** [comment]
Est-ce que vous avez pu tester ?

**Comment by catmorales** [comment]
oui 
Alors nous avons eu pas pal de problèmes mais finalement ça marche:
1/ notre service de référence  pour le fond de plan a des pbs de sld, donc nous avons utilisé un nouvel aggrégat en wms et c'est mieux
2/ vous avez passé lors du dernier commit 97a6fc2a597484e59d8fd5f17ff588dd5b580dcd la base URL de WMS à wms et notre fichier properties étant en datadir, les modifications n'avaient pas été reportées mais maintenant on obtient bien l'image. 
Par contre, on ne l'obtient qu' à la deuxième demande : 1 premier bordereau vide , on réitère la demande puis 1 deuxième bordereau ok ...
Je vous met le log à suivre

**Comment by catmorales** [comment]
Première demande:
![image](https://cloud.githubusercontent.com/assets/4659829/15929061/e8818546-2e4a-11e6-9332-3b01ba16c10b.png)

```
2016-06-09 14:02:28,000 [http-8480-4] ERROR /getImageBordereau - nouser - norole -o.a.c.i.AbstractFaultChainInitiatorObserver - Error occurred during error handling, give up!
org.apache.cxf.interceptor.Fault: org.geotools.data.DataSourceException: could not determine namespace bound to element prefix null (position: START_TAG seen ..._parcelle gml:id="app_cadastrapp_parcelle.350001000AB1460.790123">... @1:1203)

```

**Comment by catmorales** [comment]
Deuxième demande de BP sur la même sélection:
![image](https://cloud.githubusercontent.com/assets/4659829/15929103/2981ba70-2e4b-11e6-8541-674ee743bca8.png)
Fichier de log:

```
2016-06-09 14:04:33,996 [http-8480-4] INFO  /getImageBordereau - nouser - norole -o.g.c.providers.PreRequestFilter - Incoming request
2016-06-09 14:04:36,670 [http-8480-4] INFO  /getImageBordereau - nouser - norole -o.g.c.providers.PreReponseFilter - Sending response
2016-06-09 14:04:36,707 [http-8480-3] WARN  /createBordereauParcellaire - c.morales - ROLE_MOD_LDAPADMIN;ROLE_SV_ADMIN;ROLE_EL_CMS_ADMIN;ROLE_ADMINISTRATOR;ROLE_MOD_ANALYTICS;ROLE_EL_APPLIS_CAD_CNIL2;ROLE_EL_RM;ROLE_MOD_EXTRACTORAPP -org.apache.fop.apps.FOUserAgent - padding-* properties are not applicable to fo:table-body, but a non-zero value for padding was found. (See position 15:344)
2016-06-09 14:04:36,723 [http-8480-3] WARN  /createBordereauParcellaire - c.morales - ROLE_MOD_LDAPADMIN;ROLE_SV_ADMIN;ROLE_EL_CMS_ADMIN;ROLE_ADMINISTRATOR;ROLE_MOD_ANALYTICS;ROLE_EL_APPLIS_CAD_CNIL2;ROLE_EL_RM;ROLE_MOD_EXTRACTORAPP -org.apache.fop.apps.FOUserAgent - Font "Symbol,normal,700" not found. Substituting with "Symbol,normal,400".
2016-06-09 14:04:36,724 [http-8480-3] WARN  /createBordereauParcellaire - c.morales - ROLE_MOD_LDAPADMIN;ROLE_SV_ADMIN;ROLE_EL_CMS_ADMIN;ROLE_ADMINISTRATOR;ROLE_MOD_ANALYTICS;ROLE_EL_APPLIS_CAD_CNIL2;ROLE_EL_RM;ROLE_MOD_EXTRACTORAPP -org.apache.fop.apps.FOUserAgent - Font "ZapfDingbats,normal,700" not found. Substituting with "ZapfDingbats,normal,400".
2016-06-09 14:04:36,886 [http-8480-3] INFO  /createBordereauParcellaire - c.morales - ROLE_MOD_LDAPADMIN;ROLE_SV_ADMIN;ROLE_EL_CMS_ADMIN;ROLE_ADMINISTRATOR;ROLE_MOD_ANALYTICS;ROLE_EL_APPLIS_CAD_CNIL2;ROLE_EL_RM;ROLE_MOD_EXTRACTORAPP -o.g.c.providers.PreReponseFilter - Sending response

```

**Comment by MaelREBOUX** [comment]
Sous Chrome 51.0.2704.84 je reproduis : 1/ vide  2/ avec la carte

**Comment by MaelREBOUX** [comment]
C'est vraiment bizarre : je reproduis ce pb sous Chrome et Explorer 9 mais aucun souci sous FireFox.

**Comment by MaelREBOUX** [comment]
Testé à l'instant sur notre PF de test toute fraîchement redéployée : je ne reproduis avec aucun navigateur.
Je ferme donc.
