### ISSUE TITLE
getImageBordereau - org.apache.fop.fo.expr.PropertyException: Invalid URI specified

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#489]
Witnessed on latest 1.8 version:
```
20/09/2019 15:17:392019-09-20 13:17:39,241 ERROR org.apache.fop.apps.FOUserAgent - Invalid property value encountered in src="http://localhost:8080/cadastrapp/services/getImageBordereau?parcelle=2019800698000ZI0039&fillcolor=#81BEF7&fillopacity=0.6&strokecolor=#111111&strokewidth=4&basemapindex=0": org.apache.fop.fo.expr.PropertyException: Invalid URI specified (See position 1:942)
20/09/2019 15:17:39org.apache.fop.fo.expr.PropertyException: Invalid URI specified
20/09/2019 15:17:39	at org.apache.fop.fo.properties.URIProperty$Maker.make(URIProperty.java:142)
20/09/2019 15:17:39	at org.apache.fop.fo.PropertyList.convertAttributeToProperty(PropertyList.java:499)
20/09/2019 15:17:39	at org.apache.fop.fo.PropertyList.addAttributesToList(PropertyList.java:386)
20/09/2019 15:17:39	at org.apache.fop.fo.FObj.processNode(FObj.java:124)
20/09/2019 15:17:39	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291)
20/09/2019 15:17:39	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
20/09/2019 15:17:39	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
20/09/2019 15:17:39	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
20/09/2019 15:17:39	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
20/09/2019 15:17:39	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
20/09/2019 15:17:39	at org.georchestra.cadastrapp.service.pdf.BordereauParcellaireController.createBordereauParcellaire(BordereauParcellaireController.java:190)
```

**Comment by fvanderbiest** [comment]
@pmauduit says "Il y a un problème dans la construction de l'URL. Cela ne passe pas dans Jetty."
He proposes a fix:
```diff
diff --git a/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl b/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl
index 353c4cd..a572237 100644
--- a/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl
+++ b/cadastrapp/src/main/resources/xsl/bordereauParcellaire.xsl
@@ -4,6 +4,26 @@
 	xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
 	xmlns:java="http://xml.apache.org/xslt/java" exclude-result-prefixes="java">
 
+	<xsl:template name="replace-string">
+		<xsl:param name="text"/>
+		<xsl:param name="replace"/>
+		<xsl:param name="with"/>
+		<xsl:choose>
+			<xsl:when test="contains($text,$replace)">
+				<xsl:value-of select="substring-before($text,$replace)"/>
+				<xsl:value-of select="$with"/>
+				<xsl:call-template name="replace-string">
+					<xsl:with-param name="text"
+						select="substring-after($text,$replace)"/>
+					<xsl:with-param name="replace" select="$replace"/>
+					<xsl:with-param name="with" select="$with"/>
+				</xsl:call-template>
+			</xsl:when>
+			<xsl:otherwise>
+				<xsl:value-of select="$text"/>
+			</xsl:otherwise>
+		</xsl:choose>
+	</xsl:template>
 	<!-- Page layout information -->
 	<xsl:template match="/">
 		<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
@@ -71,13 +91,21 @@
 			<xsl:value-of select="dateDeValiditeEdigeo" />
 		</xsl:variable>
 		<xsl:variable name="fillColor">
-			<xsl:value-of select="style/@fillColor" />
+			<xsl:call-template name="replace-string">
+				<xsl:with-param name="text" select="style/@fillColor" />
+				<xsl:with-param name="replace" select="'#'" />
+				<xsl:with-param name="with" select="'%23'"/>
+			</xsl:call-template>
 		</xsl:variable>
 		<xsl:variable name="fillOpacity">
 			<xsl:value-of select="style/@fillOpacity" />
 		</xsl:variable>
 		<xsl:variable name="strokeColor">
-			<xsl:value-of select="style/@strokeColor" />
+			<xsl:call-template name="replace-string">
+				<xsl:with-param name="text" select="style/@strokeColor" />
+				<xsl:with-param name="replace" select="'#'" />
+				<xsl:with-param name="with" select="'%23'"/>
+			</xsl:call-template>
 		</xsl:variable>
 		<xsl:variable name="strokeWidth">
 			<xsl:value-of select="style/@strokeWidth" />
@@ -99,13 +127,13 @@
 									<xsl:attribute name="src">
 										<xsl:choose>
 											<!--  with given style -->
-											<xsl:when test="$fillColor">								
-												<xsl:value-of select="$serviceUrl" />getImageBordereau?parcelle=<xsl:value-of select="@parcelleId" /><![CDATA[&]]>fillcolor=<xsl:value-of select="$fillColor" /><![CDATA[&]]>fillopacity=<xsl:value-of select="$fillOpacity" /><![CDATA[&]]>strokecolor=<xsl:value-of select="$strokeColor" /><![CDATA[&]]>strokewidth=<xsl:value-of select="$strokeWidth" /><![CDATA[&]]>basemapindex=<xsl:value-of select="$baseMapIndex" /> 
+											<xsl:when test="$fillColor">
+                                                                                              <xsl:value-of select="$serviceUrl" />getImageBordereau?parcelle=<xsl:value-of select="@parcelleId" /><![CDATA[&]]>fillcolor=<xsl:value-of select="$fillColor" /><![CDATA[&]]>fillopacity=<xsl:value-of select="$fillOpacity" /><![CDATA[&]]>strokecolor=<xsl:value-of select="$strokeColor" /><![CDATA[&]]>strokewidth=<xsl:value-of select="$strokeWidth" /><![CDATA[&]]>basemapindex=<xsl:value-of select="$baseMapIndex" />
 											</xsl:when>
 											<!--  without style -->
-											<xsl:otherwise>			
+											<xsl:otherwise>	
 												<xsl:value-of select="$serviceUrl" />getImageBordereau?parcelle=<xsl:value-of select="@parcelleId" />
-											</xsl:otherwise>	
+											</xsl:otherwise>
 										</xsl:choose>
 									</xsl:attribute>
 								</fo:external-graphic>
```

**Comment by landryb** [comment]
So it's a jetty-only issue ? Url-encoding of the wms request to get the image to put in the PDF ?

**Comment by pmauduit** [comment]
> So it's a jetty-only issue ? Url-encoding of the wms request to get the image to put in the PDF ?

It seems so, but I did not check the behaviour on tomcat to be honest. It is likely that a filter on the servlet container does the job of encoding non-encoded chars before giving hand to the webapp in tomcat, but not in Jetty.

And my patch is pretty incomplete (also the reason why i did not send any PR here): it takes care only of the pound ('#') char of the colors parameters. Since we are using xslt 1.0 we don't have access to functions that could encode urls for us, and there are no "str-replace"-like functions, so I got no chance than using a template.

**Comment by pmauduit** [comment]
It's possible that the error was already been fixed for connected users, but not for anonymous ones:
https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/printBordereauParcellaire.js#L23-L31

vs

https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/js/printBordereauParcellaire.js#L282-L287

If it has been fixed for connected users, I'd imagine that it also arose on tomcat-based setups in the past. It still probably does not work for anonymous users.

**Comment by MaelREBOUX** [comment]
poke @pierrejego pour v1.11 ??
