### ISSUE TITLE
exception dans les logs pour infobulle si pas les droits sur l'uf

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#586]
```
User does not have enough right to see information about parcelle
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
        at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:69)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:799)
        at org.springframework.jdbc.core.JdbcTemplate.queryForMap(JdbcTemplate.java:832)
        at org.georchestra.cadastrapp.service.InfoBulleController.getInfoBulleUniteFonciere(InfoBulleController.java:173)
```

**Comment by landryb** [comment]
c'est pour le cas ou l'utilisateur fait un hover sur une parcelle pour laquelle il n'a pas les droits cnil

**Comment by landryb** [comment]
@pierrejego on peut facilement corriger ce ticket pour la v2.0 ? j'imagine que c'est mineur mais ca peut spammer les logs ;)
