### ISSUE TITLE
Impression bordereau parcellaire

### ISSUE THREAD

**Issue by pierrejego** [georchestra/cadastrapp#66]
Sur la plateforme de qualification avec modèle Arcopole, une erreur d'accès intervient lors de la récupération de la feature. Ce qui empêche de générer l'image.
La même fonctionnalité marche sur le serveur de recette interne GFI qui est sur le modèle Qgis.

```
2015-10-07 09:38:52,993 [http-8480-1] WARN  /getImageBordereau - nouser - norole -o.a.cxf.phase.PhaseInterceptorChain - Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@72d8978c
org.apache.cxf.interceptor.Fault: connect timed out
        at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163) ~[cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:129) ~[cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200) ~[cxf-rt-frontend-jaxrs-3.0.4.jar:3.0.4]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99) ~[cxf-rt-frontend-jaxrs-3.0.4.jar:3.0.4]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617) [servlet-api-2.5.jar:na]
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268) [cxf-rt-transports-http-3.0.4.jar:3.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [catalina-6.0.35.jar:6.0.35]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293) [catalina-6.0.35.jar:6.0.35]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859) [tomcat-coyote-6.0.35.jar:6.0.35]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602) [tomcat-coyote-6.0.35.jar:6.0.35]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) [tomcat-coyote-6.0.35.jar:6.0.35]
        at java.lang.Thread.run(Thread.java:679) [na:1.6.0_27]
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.6.0_27]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327) ~[na:1.6.0_27]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193) ~[na:1.6.0_27]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180) ~[na:1.6.0_27]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) ~[na:1.6.0_27]
        at java.net.Socket.connect(Socket.java:546) ~[na:1.6.0_27]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:590) ~[na:1.6.0_27]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:173) ~[na:1.6.0_27]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:409) ~[na:1.6.0_27]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:530) ~[na:1.6.0_27]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[na:1.6.0_27]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:332) ~[na:1.6.0_27]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.6.0_27]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:876) ~[na:1.6.0_27]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.6.0_27]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153) ~[na:1.6.0_27]
        at org.geotools.data.ows.SimpleHttpClient.get(SimpleHttpClient.java:100) ~[gt-main-10.8.jar:na]
        at org.geotools.data.wfs.WFSDataStoreFactory.loadCapabilities(WFSDataStoreFactory.java:856) ~[gt-wfs-10.8.jar:na]
        at org.geotools.data.wfs.WFSDataStoreFactory.createDataStore(WFSDataStoreFactory.java:475) ~[gt-wfs-10.8.jar:na]
        at org.georchestra.cadastrapp.service.ImageParcelleController.createImageBordereauParcellaire(ImageParcelleController.java:68) ~[ImageParcelleController.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_27]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.6.0_27]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.6.0_27]
        at java.lang.reflect.Method.invoke(Method.java:616) ~[na:1.6.0_27]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181) ~[cxf-core-3.0.4.jar:3.0.4]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97) ~[cxf-core-3.0.4.jar:3.0.4]
        ... 27 common frames omitted
```

Le connection timeout vient peut-être d'un manque d'authentification en https, voir dans les logs du proxy

**Comment by landryb** [comment]
Copier-coller de tests faits sur http/https transmis par mail - pour reference

---

Pour le https, si par defaut dans cadastrapp.properties je laisse la full url de geoserver avec http, je prends un 403 forbidden sur tout les acces geoserver depuis mfapp - normal ?

Par contre si j'essaie avec:
cadastre.wfs.url=/geoserver/wfs
cadastre.wms.url=/geoserver/wms

Je peux loader mfapp sans souci - apres aucun souci pour query wfs/mouseover la couche parcellaire et recup les infos.

Par contre, quand je genere le BP, evidemment je me prends un fail:

WARN  /getImageBordereau - nouser - norole -o.a.cxf.phase.PhaseInterceptorChain - Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@19b1075a
org.apache.cxf.interceptor.Fault: no protocol: /geoserver/wfs?REQUEST=GetCapabilities&version=1.0.0

Caused by: java.net.MalformedURLException: no protocol: /geoserver/wfs?REQUEST=GetCapabilities&version=1.0.0

Si dans cadastrapp.properties je force l'url en https... je me prends une exception avec mfapp en https (et pas d'image dans le BP) mais c'est plus ou moins normal vu que j'ai pas whitelisté mon propre certif

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Si mfapp est en http (et que l'url du flux est https) juste mouseover suffit a faire un code 500, qui doit etre du a la meme chose je suppose:

Etat HTTP 500 - Request processing
 failed; nested exception is java.lang.IllegalStateException: Cannot call sendError() after the response
 has been committed</u></p><p><b>description</b> <u>Le serveur a rencontré une erreur interne qui l''a
 empêché de satisfaire la requête.</u></p><p><b>exception</b></p><pre>org.springframework.web.util.NestedServletException
: Request processing failed; nested exception is java.lang.IllegalStateException: Cannot call sendError
() after the response has been committed
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:681)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:574)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
</pre>

Bref, pas mal de cas merdiques a gerer.. en attendant, je suis revenu sur mettre les 2 urls dans cadastrapp.properties avec http://fqdn

A ce stade la, je pense que le plus simple est de :
- conseiller de pas specifier le fqdn/protocole si le flux utilisé est sur le meme domaine que mfapp - et gerer ce cas en construisant l'url, ie ajouter le protocole/domain actuellement utilisé (comme ca ca marche pour http ou https)
- restreindre/forcer le full https car on est connecté ? mais du coup il faut que le certif soit ajouté dans tomcat pour qu'il s'auto-reconnaisse ? 

---

**Comment by pierrejego** [comment]
Le problème venait d'une erreur de gestion de certificat sur la plateforme, c'est maintenant corrigé. Vous pouvez avoir les bordereaux parcellaires sur la plateforme de qualification et le modèle arcopole.

Pour résumé le problème : 

1- Le client envoie une requête https à l'api pour générer le doc
2 - Le serveur reçoit la requête et faire une requête interne en http pour générer l'image (feature + fond de plan + boussole + bientôt l'échelle)
3 - Le serveur reçoit la requête de création d'image et va faire 2 nouvelles requêtes
     3.1 un appel getCapatibilities WFS en https (c'est celui ci qui posait problème)
     3.2 un appel getCapatibitilité WMS en http (dans notre cas mais ça pourrait être https)  pour récupérer le fond de plan

Pour cette appel 3.1, il manquait dans le keystore de tomcat-cadastre, le certificat du serveur frontal (devant le apache de georchestra) celui du dns fait par gfi. 

Une fois ce certificat ajouté plus de problème de génération.

Vous pouvez tester.

**Comment by landryb** [comment]
Conclusion: HTTPS/SSL/TLS, c'est toujours le cirque.

**Comment by pierrejego** [comment]
Et c'est surtout toujours compliqué à debugger....
