### ISSUE TITLE
[MFApp] Problème recherche parcelles

### ISSUE THREAD

**Issue by jusabatier** [georchestra/cadastrapp#683]
Lorsqu'on essaye de faire une recherche de parcelle par section et numero et que l'on saisit plusieurs parcelles à la fois dans le fomulaire, on a une erreur JS : 

Not enough data to call the webservice 
ext-all.js:21 Uncaught TypeError: Cannot read properties of null (reading 'addClass')
    at constructor.processRows (ext-all.js:21:650907)
    at constructor.insertRows (ext-all.js:21:657381)
    at constructor.onAdd (ext-all.js:21:664539)
    at h.Event.fire (ext-all.js:21:3699)
    at constructor.fireEvent (ext-all.js:21:687)
    at constructor.add (ext-all.js:21:312887)
    at Object.<anonymous> (cadastrapp.js:31:458)
    at Object.each (ext-base.js:21:6081)
    at GEOR.Addons.Cadastre.addResultToTab (cadastrapp.js:31:286)
    at success (cadastrapp.js:180:414)

Et du coup, seul la première parcelle est prise en compte pour le zoom et le recentrage.

**Comment by jusabatier** [comment]
Vu que le support de MFapp n'est plus d'actualité je ferme.
