### ISSUE TITLE
NPE au redemarrage de tomcat

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#75]
tomcat8 sur debian jessie

```
2015-10-23 08:41:31,045 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] INFO  / - nouser - norole -o.s.w.c.s.XmlWebApplicationCont
ext - Closing Root WebApplicationContext: startup date [Fri Oct 09 15:23:23 CEST 2015]; root of context hierarchy
2015-10-23 08:41:31,048 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] WARN  / - nouser - norole -o.s.w.c.s.XmlWebApplicationCont
ext - Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.NullPointerException: null
        at org.apache.catalina.webresources.AbstractArchiveResource.getContent(AbstractArchiveResource.java:163) ~[tomcat8-catalina-8.0.14.
jar:8.0.14]
        at org.apache.catalina.loader.WebappClassLoaderBase.findResourceInternal(WebappClassLoaderBase.java:2560) ~[tomcat8-catalina-8.0.14
.jar:8.0.14]
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2383) ~[tomcat8-catalina-8.0.14.ja
r:8.0.14]
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:852) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1262) ~[tomcat8-catalina-8.0.14.jar:8.0.14
]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1145) ~[tomcat8-catalina-8.0.14.jar:8.0.14
]
        at org.apache.cxf.endpoint.ServerImpl.stop(ServerImpl.java:168) ~[ServerImpl.class:3.0.4]
        at org.apache.cxf.endpoint.ServerImpl.destroy(ServerImpl.java:180) ~[ServerImpl.class:3.0.4]
        at org.apache.cxf.bus.managers.ServerRegistryImpl.preShutdown(ServerRegistryImpl.java:90) ~[ServerRegistryImpl.class:3.0.4]
        at org.apache.cxf.bus.managers.CXFBusLifeCycleManager.preShutdown(CXFBusLifeCycleManager.java:97) ~[CXFBusLifeCycleManager.class:3.
0.4]
        at org.apache.cxf.bus.extension.ExtensionManagerBus.shutdown(ExtensionManagerBus.java:327) ~[ExtensionManagerBus.class:3.0.4]
        at org.apache.cxf.bus.extension.ExtensionManagerBus.shutdown(ExtensionManagerBus.java:314) ~[ExtensionManagerBus.class:3.0.4]
        at org.apache.cxf.bus.spring.SpringBus.onApplicationEvent(SpringBus.java:113) ~[SpringBus.class:3.0.4]
        at org.apache.cxf.bus.spring.SpringBus$1.onApplicationEvent(SpringBus.java:62) ~[SpringBus$1.class:3.0.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~
[SimpleApplicationEventMulticaster.class:4.1.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~
[SimpleApplicationEventMulticaster.class:4.1.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) [AbstractApplic
ationContext.class:4.1.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869) [AbstractApplication
Context.class:4.1.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836) [AbstractApplicationCo
ntext.class:4.1.6.RELEASE]
        at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:579) [ContextLoader.class:4.1.6.RELE
ASE]
        at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:115) [ContextLoaderListener.cl
ass:4.1.6.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4838) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5438) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:827) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.startup.HostConfig.undeploy(HostConfig.java:1325) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1273) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1473) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:280) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1141) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1377) [tomcat8-catalina-8
.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1381) [tomcat8-catalina-8
.0.14.jar:8.0.14]
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1349) [tomcat8-catalina-8.0.14.jar:8.
0.14]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
2015-10-23 08:41:31,050 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] WARN  / - nouser - norole -o.s.b.f.s.DisposableBeanAdapter
 - Invocation of destroy method 'destroy' failed on bean with name 'services': java.lang.NullPointerException

```

**Comment by pierrejego** [comment]
@landryb a prévu de rajouter des détails sur la technique de déploiement, car je ne reproduis pas chez moi

**Comment by landryb** [comment]
Dans mes logs j'ai cette erreur 5 fois, dont la derniere le 5 novembre. touch cadastrapp/WEB-INF/web.xml redemarre correctement l'appli.

**Comment by landryb** [comment]
Un redémarrage de tomcat ne reproduit pas - je vais fermer et réouvrirait si ca revient.
